### ISSUE TITLE
Can't compile because: 'IRLinterrupt' was not declared in this scope

### ISSUE THREAD

**Issue by oceb1** [dmonty2/44key_remote_leds#1]
The problematic code seems to be
`attachInterrupt(digitalPinToInterrupt(PIN_IR),IRLinterrupt<IR_NEC>, CHANGE);`

The output is
```
error: expected primary-expression before ',' token

   attachInterrupt(digitalPinToInterrupt(PIN_IR), IRLinterrupt<IR_NEC>, CHANGE);

                                                                     ^

exit status 1
'IRLinterrupt' was not declared in this scope
```

I tried different versions of Arduino and IRLremote and don't have any other idea how to fix this.

**Comment by dmonty2** [comment]
Seems to be the IRLremote was in an early dev state when it was used for this project.  I'll have to find some free time to integrate the newer libraries.

Here are older libraries.
https://github.com/NicoHood/IRLremote/tree/7dfa723d4459818eb616b43dda266ea55791afd4/src
Maybe I'll also upload the older ones as well.

**Comment by dmonty2** [comment]
[IRLremote.zip](https://github.com/dmonty2/ir_remote_leds/files/982339/IRLremote.zip)
Here is the library I used when it was built a few years ago.

I had a look at the header and example files.  He did a re-write of most of the IRLremote API.  When I get time I will have to re-write the code to work with his new API.

**Comment by dmonty2** [comment]
This bug has now been fixed.
